FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC
RUN apt-get update && apt-get install -y software-properties-common python3-pip ssh ansible openssh-client tzdata
RUN useradd -ms /bin/bash ansible
USER ansible
WORKDIR /home/ansible
